services:
  legal_processor_worker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: legal_processor_worker
    volumes:
      # Maps your local host directories directly into the container's active working directory
      - ./data:/app/data
      - ./fml-raw-legal-store:/app/fml-raw-legal-store
    restart: on-failure