site_name: "Ministry of Power"
forum: "MOP"
state: "CENTRAL"
jurisdiction: "Central - India"
category: "Acts & Rules"
document_type: "Act/Policy"
base_url: "https://powermin.gov.in"
start_url: "https://powermin.gov.in/en/content/electricity-act-2003"

selectors:
  row: ".field-items .field-item ul li"
  title: "self" 
  link: "a"
  table_row: "table.table tbody tr"
  table_title: "td:nth-child(2)"
  table_link: "td:nth-child(2) a"