site_name: "TNERC"
forum: "TNERC"
state: "TN"
jurisdiction: "India"
category: "Regulations"
base_url: "http://exam.tnebnet.org"
start_url: "http://exam.tnebnet.org/exambooks/TO1B2.pdf" 

selectors:
  row: "body" 
  title: "text" 
  link: "self"